name: Release Workflow

on:
  workflow_run:
    workflows: ["Lemonade CI Builds"]
    types:
      - completed

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.name == 'Lemonade CI Builds'
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Windows MSVC Artifact
        uses: actions/download-artifact@v2
        with:
          name: Windows_MSVC
          path: artifacts/
      
      - name: Download Linux AppImage Artifact
        uses: actions/download-artifact@v2
        with:
          name: Linux_AppImage
          path: artifacts/
      
      - name: Download Android APK Artifact
        uses: actions/download-artifact@v2
        with:
          name: Android APK
          path: artifacts/
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Description of the release goes here.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the repository's secret token
      
      - name: Upload Windows MSVC Artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/Windows_MSVC.zip
          asset_name: Windows_MSVC.zip
          asset_content_type: application/zip
      
      - name: Upload Linux AppImage Artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/Linux_AppImage.AppImage
          asset_name: Linux_AppImage.AppImage
          asset_content_type: application/octet-stream
      
      - name: Upload Android APK Artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/Android_APK.apk
          asset_name: Android_APK.apk
          asset_content_type: application/vnd.android.package-archive
          
